### PR TITLE
fix: Enhancement of Visual Json Schema Editor

### LINKED ISSUE #1023: Enhance the Visual JSON Schema Editor
After merging: https://github.com/asyncapi/studio/pull/905
The visual editor needs to be enhanced for production

## Scope
- [ ] Look & Feel
- [ ] Deletion
- [ ] Nested objects
- [ ] Test functionality

## Complexity
Medium

### PR DESCRIPTION
**Pull request by Gmin2**
**Description**

-  [✅ ] Added Delete Property Function
-  [✅ ] Changed Type of Property Function
-   [✅] Toggle Required/NotRequired Function
-  [ ✅] UI
 -  [✅ ] Added Property function, but only for cases which have a path containing array<object>

**Related issue(s)**
Resolves #1023

### CODE REVIEW

**Comment by utnim2** [comment]
Hey @princerajpoot20 it is done and ready for review

cc @Amzani

**Review by princerajpoot20 — CHANGES_REQUESTED** [review]
Good work @utnim2 .

Have you tested this with all the sample JSON schemas?

- There is no option to `add property` to the `array<object>` type.
- In the UI for array properties, we should not have `Array Items` as text.
- If we are changing the type of an existing property, when I change it to type array of string, it directly assigns the same value. For example: `"type": "array<string>"`.

Instead, it should be like
```
"type": "array",
  "items": {
    "type": "number"
  }
```

Could you make the code editor text be `beautify` after performing any operation

**Comment by utnim2** [comment]
Done all the reviewed changes @princerajpoot20 

> Could you make the code editor text be `beautify` after performing any operation

could you explain this more what exactly do you want, ig i have matched the design provided

**Comment by princerajpoot20** [comment]
Screenshot 2024-04-16 at 7 10 40 PM
Screenshot 2024-04-16 at 7 10 50 PM


@utnim2 After modification, the JSON schema is not in a readable form.

- In the schema shown in Figma, the `friends` array can have two data types: integer or null. We should make it accordingly.
- In the above case, if we consider creating **this** JSON schema using a visual editor, we currently cannot make the `friends` array support more than one value. To address this, we could add a multiselect checklist or something similar in the `add property` field, allowing us to select two data types when adding a property.
- Some UI changes are still needed, such as the colors for arrays and objects being different in `array<object>`, and the colors, font size and font style are not exactly matching those in Figma.



Screenshot 2024-04-16 at 7 23 27 PM

After having array<object> , in next line we again mention object.

Screenshot 2024-04-16 at 7 24 09 PM

This text is there if root is of type array

Screenshot 2024-04-16 at 7 24 22 PM

This text can be removed

File: packages/ui/components/VisualEditor/SchemaProperty.tsx [hunk 1]
```diff
@@ -120,7 +169,10 @@ const SchemaProperty: React.FC<SchemaPropertyProps> = ({
             <option value="number">Number</option>
             <option value="boolean">Boolean</option>
             <option value="object">Object</option>
-            <option value="array">Array</option>
+            <option value="array<string>">Array&lt;String&gt;</option>
+            <option value="array<number>">Array&lt;Number&gt;</option>
+            <option value="array<boolean>">Array&lt;Boolean&gt;</option>
+            <option value="array<object>">Array&lt;Object&gt;</option>
```
Comment (princerajpoot20) [inline packages/ui/components/VisualEditor/SchemaProperty.tsx:175]: I would suggest that we should not use this type of array as a multiple option. We should have an single array than  selecting its type. It will look cleaner.

File: packages/ui/components/VisualEditor/SchemaProperty.tsx [hunk 2]
```diff
@@ -18,6 +17,32 @@ interface SchemaPropertyProps {
...
+      return 'red';
+    } else if (itemType === 'number') {
+      return 'red';
+    } else if (itemType === 'boolean') {
+      return 'red';
+    } else if (itemType === 'object') {
+      return 'red';
+    } else {
+      return 'white'; 
+    }
```
Comment (princerajpoot20) [inline packages/ui/components/VisualEditor/SchemaProperty.tsx:40]: The color is not specific for array, it is common.

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by Amzani** [comment]
@utnim2 thanks for working on this, could you check the failed tests?

**Comment by utnim2** [comment]
> @utnim2 thanks for working on this, could you check the failed tests?

Looking into it

File: packages/ui/components/VisualEditor.tsx [hunk 3]
```diff
@@ -43,6 +37,14 @@ export const VisualEditor: React.FC<VisualEditorProps> = ({ schema, onSchemaChan
     onSchemaChange(newSchemaString);
   };
 
+  const selectStyle = {
```
Comment (KhudaDad414) [inline packages/ui/components/VisualEditor.tsx:40]: Instead of styling the select like this, I suggest we use the `DropDownMenu` item that we already have in the our `ui` package. the `trigger` can also be what is already in the figma design easily.

File: packages/ui/components/VisualEditor.tsx [hunk 4]
```diff
@@ -43,6 +37,14 @@ export const VisualEditor: React.FC<VisualEditorProps> = ({ schema, onSchemaChan
...
+    backgroundColor: '#0F172A',
+    color: getColorForType(schemaObject.type || 'white', schemaObject.items?.type || 'red'),
+    borderRadius: '3px',
+    fontSize: '12px',
+    fontFamily: 'Inter, sans-serif'
+  };
+
   const renderRootTypeSelector = () => (
```
Comment (KhudaDad414) [inline packages/ui/components/VisualEditor.tsx:48]: for some reason this doesn't work on my machine. and selecting `array` gives an error.

**Review by KhudaDad414 — COMMENTED** [review]
Left some comments.

**Comment by utnim2** [comment]
Currently my end sem exams are going on and it will finish in 6th of may. I will be able to do the rest of the work in the next two weeks max
**Todo** - some changes as reviwed by @KhudaDad414 and @princerajpoot20 

If @aeworxet you can  extend the finish date of the issue by 1 week it would be enough

**Comment by Gmin2** [comment]
Some modifications are needed , not ready for a fresh review

**Comment by KhudaDad414** [comment]
@Gmin2 what do you think about converting the Json Schema to a tree first? it would make the implementation a lot easier. https://github.com/stoplightio/json-schema-tree

**Comment by Gmin2** [comment]
> @Gmin2 what do you think about converting the Json Schema to a tree first? it would make the implementation a lot easier. https://github.com/stoplightio/json-schema-tree

What are you thinking about it?
I dont get the point why to do this(I may be naive here), I was thinking of parsing it to a schema validator(like ajv)

**Comment by Gmin2** [comment]
Can i get a review 
cc @Amzani @princerajpoot20 @KhudaDad414

**Comment by KhudaDad414** [comment]
> What are you thinking about it?

@Gmin2 the main benefit that we get is that traversing a tree much easier than a object. plus, that library will handle `allOf` and `anyOf` and `$ref` fields for us. which is a real pain to work with.

File: packages/ui/components/DropdownMenu.tsx [hunk 5]
```diff
@@ -18,6 +18,9 @@ interface DropdownMenuProps {
   items: DropdownMenuItem[]
   side?: 'top' | 'right' | 'bottom' | 'left'
   align?: 'start' | 'center' | 'end'
+  multiple?: boolean
+  selectedOptions?: string[]
```
Comment (KhudaDad414) [inline packages/ui/components/DropdownMenu.tsx:22]: what is the point of adding these here if we are not using them?

File: packages/ui/components/VisualEditor/SchemaObject.tsx [hunk 6]
```diff
@@ -22,27 +22,88 @@ const SchemaObject: React.FC<SchemaObjectProps> = ({
...
+    }
+  
+    onSchemaChange(updatedSchema);
+  }
+  
+  const handleToggleNestedRequired = (path: string, name: string) => {
+    const updatedSchema = _.cloneDeep(schema);
+    const normalizedPath = path.startsWith('.') ? path.slice(1) : path;
+    const schemaPath = normalizedPath.split('.properties');
+    console.log("schemaPath",schemaPath)
```
Comment (KhudaDad414) [inline packages/ui/components/VisualEditor/SchemaObject.tsx:89]: I think we should remove these logs.
```suggestion
```

File: packages/ui/components/VisualEditor/PropertyControls.tsx [hunk 7]
```diff
@@ -32,57 +33,114 @@ const PropertyControls: React.FC<PropertyControlsProps> = ({ onAdd, schemaPath,
...
-            <option value="">Select item type</option>
-            <option value="string">String</option>
-            <option value="number">Number</option>
-            <option value="boolean">Boolean</option>
-            <option value="object">Object</option>
-          </select>
+          {!showInputs && (
+              <button onClick={() => setShowInputs(true)} className='text-[#808080] px-2 py-2 rounded-md flex items-center gap-2 font-inter text-sm'>
+              <div className="text-[#808080] border-2 border-[#808080] h-5 w-5 rounded-full flex items-center justify-center">
+              <span>&#43;</span>
```
Comment (KhudaDad414) [inline packages/ui/components/VisualEditor/PropertyControls.tsx:102]: We can use the `AddIcon` that is already present in `icons` folder.

File: packages/ui/components/VisualEditor/SchemaObject.tsx [hunk 8]
```diff
@@ -22,27 +22,88 @@ const SchemaObject: React.FC<SchemaObjectProps> = ({
...
+    } else {
+      const newRequired = existingRequired.filter((item: string) => item !== name);
+      _.set(updatedSchema, requiredPath, newRequired);
+    }
+  
+    onSchemaChange(updatedSchema);
+  };
+
   return (
     <div style={{ margin: '10px 0' }}>
```
Comment (KhudaDad414) [inline packages/ui/components/VisualEditor/SchemaObject.tsx:108]: we can use https://www.radix-ui.com/primitives/docs/components/collapsible to collapse the Objects and arrays.

Screenshot 2024-05-20 at 12 20 48

**Review by KhudaDad414 — CHANGES_REQUESTED** [review]
Left some suggestions.

**Comment by Gmin2** [comment]
> @Gmin2 the main benefit that we get is that traversing a tree much easier than a object. plus, that library will handle `allOf` and `anyOf` and `$ref` fields for us. which is a real pain to work with.
> but I guess we can iterate one more time on this component and solve this problems there.

@KhudaDad414 i will do it in the follow up PR

**Comment by Gmin2** [comment]
@KhudaDad414 done with all the changes

**Comment by princerajpoot20** [comment]
@Gmin2 deploy is failing. Could you check that?

**Comment by Gmin2** [comment]
> @Gmin2 deploy is failing. Could you check that?

fixed  👍

File: packages/ui/components/DropdownMenu.tsx (hunk 5 above)
Comment (KhudaDad414) [reply packages/ui/components/DropdownMenu.tsx:22]: In the end, we surely do. but for now I think it makes sense to remove these from the interface since the entire `DropDownMenu` is not handling these options.

Comment (KhudaDad414) [reply packages/ui/components/DropdownMenu.tsx:22]: @Gmin2 can you remove the changes to this component?

Comment (Gmin2) [reply packages/ui/components/DropdownMenu.tsx]: Done @KhudaDad414

**Review by KhudaDad414 — APPROVED** [review]
LGTM

**Comment by princerajpoot20** [comment]
@Gmin2, Good work! Just a few changes:
1. We are not able to build the JSON schema **from scratch**.
    - In the case of an empty JSON schema `{}`, we should only have the option to define the root type. We should not have the `add property` option there. It should be there only for the type defined as `object` or `array-object`.


Like for example:
```
{
      "type": "string"
}
```
In this JSON schema, we will not have an `add property` option, as we cannot add a property anywhere in this JSON schema since the root is of type string.

2. The `add property` option is not working correctly in cases where the root is of type `array-object`. If we try to add a property to that schema, it changes the root type from `array-object` to `object`.

3. The UI doesn't support selecting multiple data types while adding a new property.

4. After modification from the visual editor, the code editor (JSON schema) is not in a readable form.

**Comment by Gmin2** [comment]
> The UI doesn't support selecting multiple data types while adding a new property.

as we are using radix Dropdown component (can you check [this](https://github.com/radix-ui/primitives/issues/1270#issuecomment-1231792982)), not sure if we can implement it, we might have a workaround but i am constantly trying with introducing state but multi-select is not working.

cc @princerajpoot20

**Comment by princerajpoot20** [comment]
> it is same as was before the changes that i have made

I have tested this through the [Netlify deploy link](https://deploy-preview-1065--asyncapi-studio-design-system.netlify.app/) in the PR, there it is not rendering in a readable form.
Screenshot 2024-05-27 at 11 17 24 PM

**Comment by Gmin2** [comment]
> I have tested this through the [Netlify deploy link](https://deploy-preview-1065--asyncapi-studio-design-system.netlify.app/) in the PR, there it is not rendering in a readable form.
> 

netlify is not rendering the latest commits, you can use github cli and then see the changes

**Comment by princerajpoot20** [comment]
It is not that Netlify has not rendered your latest commit. It automatically takes your latest commit. Their problem is something else.

Screenshot 2024-05-28 at 1 56 06 AM

**Comment by Gmin2** [comment]
> If the changes are not visible in the PR preview, then they will not be visible in deployment (after merge) either.

it is working fine in my machine

**Comment by Gmin2** [comment]
Hey @princerajpoot20 in the deploy preview also it is showing right 

image

**Comment by princerajpoot20** [comment]
@Gmin2 I'm talking about editor after making changes through visual editor.
Ref::

https://github.com/asyncapi/studio/assets/44585452/49e10ca9-4c6f-4cbd-bdac-bed25cd4fa72

**Comment by KhudaDad414** [comment]
@princerajpoot20 is that necessary? we will have something nicer like a Codemirror editor and an easy-to- edit format like YAML over there anyway.

File: packages/ui/components/DropdownMenu.tsx [hunk 9]
```diff
@@ -18,6 +18,7 @@ interface DropdownMenuProps {
   items: DropdownMenuItem[]
   side?: 'top' | 'right' | 'bottom' | 'left'
   align?: 'start' | 'center' | 'end'
+  onSelect?: (options: string[]) => void
```
Comment (KhudaDad414) [inline packages/ui/components/DropdownMenu.tsx:21]:
```suggestion
```

File: packages/ui/components/DropdownMenu.tsx [hunk 10]
```diff
@@ -44,6 +45,7 @@ export const DropdownMenu: FunctionComponent<DropdownMenuProps> = ({
   items,
   side,
   align,
+  onSelect
```
Comment (KhudaDad414) [inline packages/ui/components/DropdownMenu.tsx:48]:
```suggestion
```

**Review by KhudaDad414 — CHANGES_REQUESTED** [review]
LGTM!

**Comment by princerajpoot20** [comment]
> @princerajpoot20 is that necessary? we will have something nicer like a Codemirror editor and an easy-to- edit format like YAML over there anyway.

@KhudaDad414 Sure, this sounds good.

File: packages/ui/components/DropdownMenu.tsx (hunk 9 above)
Comment (Gmin2) [reply packages/ui/components/DropdownMenu.tsx:21]: @KhudaDad414 onSelect prop is being used at PropertyControl.tsx and at VisualEditor.tsx

**Review by KhudaDad414 — DISMISSED** [review]

**Review by KhudaDad414 — DISMISSED** [review]
LGTM

**Comment by KhudaDad414** [comment]
@princerajpoot20 pingy pongy.

**Review by princerajpoot20 — DISMISSED** [review]
LGTM

**Review by princerajpoot20 — APPROVED** [review]
LGTM

**Review by KhudaDad414 — APPROVED** [review]
LGTM
