### PR TITLE
fix: point to the latest version in ConvertToLatestModal

### LINKED ISSUE #391: when convention modal shows up it should recommend latest version for convertion
#### Reason/Context

When I paste document in asyncapi version prior 2.4 I get 👇🏼 

Screenshot 2022-07-21 at 12 53 09

This is super cool, but I'd love to improve my experience, and have the latest version preselected, so by default I'd like to see 👇🏼 

Screenshot 2022-07-21 at 12 54 26

This would be uber cool

### PR DESCRIPTION
**Pull request by nawed2611**
**Description**
- ``` ConvertToLatesModal ``` takes the latest version of AsyncAPI as the default value

image
Case shown in Screenshot- When the AsyncApi version is set to 1.0.0

**Related issue(s)**
Fixes #391

### CODE REVIEW

File: src/components/Modals/ConvertToLatestModal.tsx [hunk 1]
```diff
@@ -114,10 +114,10 @@ export const ConvertToLatestModal: React.FunctionComponent = () => {
               onChange={e => setVersion(e.target.value)}
               value={version}
             >
-              <option value="">Please Select</option>
-              {reservedAllowedVersions.map(v => (
-                <option key={v} value={v}>
-                  {v === latestVersion ? `${v} (latest)` : v}
+              <option value={latestVersion} key={latestVersion}>{latestVersion} (latest)</option>
+              {reservedAllowedVersions.filter((v) => v !== latestVersion).map(v => (
+                <option key={v} value={v}  >
```
Comment (magicmatatjahu) [inline src/components/Modals/ConvertToLatestModal.tsx:119]:
```suggestion
                <option key={v} value={v}>
```

**Review by magicmatatjahu — CHANGES_REQUESTED** [review]
Good, but I should have possibility to convert given spec when modal is opened (and I didn't change destination version). Now, `Convert` button is disabled, it should by now enabled by default.

image

**Comment by nawed2611** [comment]
> Good, but I should have possibility to convert given spec when modal is opened (and I didn't change destination version). Now, `Convert` button is disabled, it should be enabled by default.
> 
> image

This should get solved by (As there is a default version selected) -

image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by magicmatatjahu — APPROVED** [review]
@nawed2611 Thanks for PR!

**Comment by magicmatatjahu** [comment]
@all-contributors please add @nawed2611 for code,bug

**Comment by magicmatatjahu** [comment]
https://github.com/all-contributors please add @nawed2611 for code, bug

**Comment by magicmatatjahu** [comment]
@all-contributors please add @nawed2611 for code, bug
